### ISSUE TITLE
Kind parameter in Eval Layer

### ISSUE THREAD

**Issue by Atticus1806** [rwth-i6/returnn_common#12]
Currently the `kind` parameter for the Eval layer needs to be set to `"eval"` by hand, otherwise the `super()` call to the `Combine` layer is missing a parameter. Maybe it would be a good idea to add this as a default parameter to the `Eval` layer? This should not change in any usecase of the eval layer.

Again: Does this require some special case handling (if so, again through modifying `_init_args`) or can we handle it in another way?

**Comment by albertz** [comment]
> Currently the `kind` parameter for the Eval layer needs to be set to `"eval"` by hand, otherwise the `super()` call to the `Combine` layer is missing a parameter. Maybe it would be a good idea to add this as a default parameter to the `Eval` layer? This should not change in any usecase of the eval layer.

The `EvalLayer` does not even accept the `kind` argument.

The problem is that the `Eval` maker inherits from `Combine` maker, and the current code assumes that a derived layer class just adds arguments, but does not remove any.

> Again: Does this require some special case handling (if so, again through modifying `_init_args`) or can we handle it in another way?

There are almost always an infinite number of possible ways things can be handled. So that is not the question.
The question is, what ways we can think of, and which of those is the best approach, where best means simple, clear, generic and flexible. Although we will not always find optimal solutions.

In this case, yes, treating this as a special case is one option.

More generic would be to try to detect this more automatically. We would need to find and parse the `super(...).__init__(...)` call in the code, and there we could see that `kind="eval"` is set explicitly.

We could also maybe restructure the code on RETURNN side, and not inherit `EvalLayer` from `CombineLayer` (I was not so sure if this is so nice anyway).

And I'm sure there are more ways which I cannot think of right now.

---

Off topic here but still related: I think the `EvalLayer` is actually not really needed so often, or at all in this new framework. E.g. `LayerRef` was supposed to also have basic operations like `__add__` etc. And I think we should also wrap most common/potential functions (similar as PyTorch).

**Comment by Atticus1806** [comment]
Actually I just now realize, that this unfortunately was not fixed by this. The problem now is, that when calling the eval layer, when calling `get_opts` this calls `**super().get_opts()` which returns a dictionary which has an entry `kind: 'eval'`. This doesn't cause an error in returnn_common, but in RETURNN, since RETURNN ist not able to handle a "set" 'kind' parameter in that layer. So returnn_common generates for example: `'eval': {'class': 'eval', 'from': 'x', 'eval': "y", 'kind': 'eval'}` which causes the error:
`TypeError: __init__() got multiple values for keyword argument 'kind'`

At this stage I am not sure how to handle this. Maybe checking on RETURNN side, wether kind: 'eval' is set and otherwise set it? What do you think?

**Comment by albertz** [comment]
It means we need to fix `get_opts` for such cases. I.e. the `get_super_call_code_str` (from #14) needs to store the list of params it explicitly sets (the `key`s in `tup_ls` at the end), and then those need to be removed in `get_opts`.

But I would add this extra logic in `get_opts` only to those layers where such extra logic is needed.

I'm not sure if this gets ugly or not.

**Comment by Atticus1806** [comment]
>I.e. the get_super_call_code_str (from #14) needs to store the list of params it explicitly sets (the keys in tup_ls at the end), and then those need to be removed in get_opts

That would assume though, that all these parameters passed in the super call, are really also set in the `get_opts` of the parent layer right? This might be an assumption we can make, but still I think we might need to be careful here. Maybe only manually doing it for certain layers might be smart yes. Currently eval layer is the only case I found where this happens.

**Comment by albertz** [comment]
No, you don't need to make those assumption. You can just in any case remove these params from `get_opts`.
So in `get_opts`, you would also have sth like:
`opts.pop("eval", None)`

But, isn't that assumption always true? If it is passed to the `super.init` call, it implies that the base class has this option, or not? Thus I would first make the assumption, such that we get sth like:
`del opts["eval"]`

**Comment by Atticus1806** [comment]
>But, isn't that assumption always true?

Thats what I am asking pretty much, whether there are params excluded from this "rule" that if the base class gets the parameter that its also included in the opts dict.
Then deleting should be fine yes.

**Comment by albertz** [comment]
I pushed sth which should fix it.
