### ISSUE TITLE
GPU OOM when running Transformer model

### ISSUE THREAD

**Issue by JackTemaki** [rwth-i6/returnn_common#139]
I tried to run a Experiment with the Transformer implementation of `returnn_common`, but the training directly went OOM on the GPU memory.

It is a 6 encoder - 6 decoder layer model with size 512 resulting in only 36M parameters, so fairly small. The batch size was 10000. My old transformer models used to run with batch size 20000. Audio data and labels are identical.

I do not have much additional information yet, I will append it here if I have more details.

**Comment by albertz** [comment]
ASR? Do you apply downsampling?

**Comment by albertz** [comment]
Note that I had also OOM problems in some earlier Conformer implementation. This was due to a bug in the downsampling of the Conformer, where there was `merge_dims` on the spatial dims, resulting in a huge spatial dim. The `merge_dims` was supposed to only operate on the static dims. This is fixed now. With Conformer, the memory consumption looks normal. So I wonder why Transformer is different. Maybe the decoder.

**Comment by JackTemaki** [comment]
Yes you are right, downsampling is wrong!
