### ISSUE TITLE
Calling Module twice results in error

### ISSUE THREAD

**Issue by Atticus1806** [rwth-i6/returnn_common#3]
Hey, I am writing this issue to clarify wether this indeed is intended behavior (and maybe the error message should be clarified or caught somewhere else) or wether this actually is not correct:
When Building a Module and calling it after initialization and the first call a second time results in an assertion error. 
`assert cur_scope_abs[0] is self_name_abs[0]  # same root`
Steps to reproduce: 
```
class TestBlock(Module):

  def __init__(self, l2=1e-07, dropout=0.5, n_out=128):
    super().__init__()
    self.linear = layers.Linear(n_out=n_out, l2=l2, dropout=dropout,  with_bias=False, activation=None)

  def forward(self, x: LayerRef, *args, **kwargs) -> LayerRef:
    x = self.linear(x, name="test")
    return x
x = TestBlock()
y = x("test")
z = x("test2")
```
The last line causes the assertion error. Right now I cannot say wether actually calling it twice makes sense, if not maybe the message can be clarified. I caused the error by accident and went into debugging, thinking my built class had an error.

**Comment by albertz** [comment]
There were multiple bugs. Both in your code and also in the naming logic.

I think I fixed the bugs. Maybe we should add some more test cases to test some more individual cases. Maybe we also should clean it up a bit. But let's open separate issues whenever there is some new problem.

I also fixed your code example, and added it as a test case [here](https://github.com/rwth-i6/returnn_common/blob/3843406102a02402d40e6dd9935167fd4fa9554f/tests/test_models_layers.py).

Problems in your code:

* You do not have a root context. You can either use one module as a root context itself (so it corresponds to the main network dict itself), or you set up a unnamed root context.

  I extended the documentation slightly to explain this more. Is this clear now?

* `"test"` or `"test2"` is not a `LayerRef`. You cannot simply use a string for this. Use the functions from the `base` module, e.g. `get_extern_data(data_key: str) -> LayerRef`. `LayerRef` is some internal reference. The internal details of `LayerRef` should never matter for the user because the user would always use some other function which creates such `LayerRef`.

* You do not need the `*args, **kwargs` in your `forward`. So do not add it when you do not use it (unless you have a good reason for it).

* You do not need `name="test"` when you call some module/layer. The idea is that the layer name is determined by the attribute name in the module. Which is `linear` in your example. So `linear` becomes the layer name (not in your example because `name="test"` overwrites this logic). This is the standard PyTorch module style. Normally you never should need to explicitly set `name` unless there is some good reason.

Maybe the documentation should be extended to clarify all of this. PRs are welcome.
